### PR TITLE
Attempt to fix bendpoint issue

### PR DESCRIPTION
**Pull request by jbsarrodie**
Test this. It needs some slight changes in bpweight calculation but it works.

### CODE REVIEW

**Comment by Phillipus** [comment]
Amazing! Thanks very much, dude. :-)

**Comment by jbsarrodie** [comment]
Where there's some math, there's a way ;-)

**Comment by Phillipus** [comment]
Comparing the original bendpoints with the ones exported and then imported there's about 1 pixel difference but this may be a rounding error. Close enough, though. ;-)

**Comment by Phillipus** [comment]
Also need to convert to absolute point on export and then convert from absolute to relative on import ;-)

**Comment by jbsarrodie** [comment]
_Also need to convert to absolute point on export and then convert from absolute to relative on import ;-)_

That's what your original XMLModelmporter#addBendpoints() do, isn't it ?

**Comment by Phillipus** [comment]
I think the exporter might work with this:

IBounds srcBounds = getAbsoluteBounds(connection.getSource()); // get bounds of source node

IBounds tgtBounds = getAbsoluteBounds(connection.getTarget()); // get bounds of target node

But not sure about importing. The method IBounds getRelativeBounds(IBounds absoluteBounds, IDiagramModelObject dmo) might not be suitable.

**Comment by jbsarrodie** [comment]
If you want to play, test with those attached files (confidential material,
so please do not share, blah, blah, blah...)

JB

2015-01-29 22:22 GMT+01:00 Phil Beauvoir <notifications@github.com>:

**Pull request merged**
